name: My First CI

on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:
    files-check:
        runs-on: ubuntu-latest
        defaults:
          run: 
            working-directory: src  

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Check index.html
              run: test -f index.html

            - name: Check feed.html
              run: test -f feed.html

            - name: Say hello
              run: echo "Hello from Github Actions !"

            - name: Show current directory
              run: pwd

            - name: Show files
              run: ls -la

            - name: Success
              run: echo "Website validation successful!"